version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: cafe_postgres
    restart: always
    environment:
      POSTGRES_USER: cafe_user
      POSTGRES_PASSWORD: cafe_pass
      POSTGRES_DB: cafe_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: cafe_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pg_data:


# http://localhost:8080/?pgsql=postgres